version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "07:50"
      timezone: "Europe/London"
    groups:
      github-actions-dependencies:
        applies-to: all
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/javascript"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "07:50"
      timezone: "Europe/London"
    groups:
      npm-dependencies:
        applies-to: all
        patterns:
          - "*"

  - package-ecosystem: "bundler"
    directory: "/ruby"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "07:50"
      timezone: "Europe/London"
    groups:
      ruby-dependencies:
        applies-to: all
        patterns:
          - "*"
