version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions-dependencies:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/javascript"
    schedule:
      interval: "weekly"
    groups:
      npm-dependencies:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "bundler"
    directory: "/ruby"
    schedule:
      interval: "weekly"
    groups:
      ruby-dependencies:
        applies-to: security-updates
        patterns:
          - "*"
